server:
  port: 9005

spring:
  application:
    name: WEB-APP
#  cloud:
#    gateway:
#      routes:
#        - id: API-GATEWAY
#          uri: lb://API-GATEWAY
#          predicates:
#            - Path=/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

