server:
  port: ${port:9001}


spring:
  application:
    name: CLINIC-SERVICE

#services:
 # db:
  #  image: postgres
   # ports:
    #  - 5000:5432
    #environment:
     # POSTGRES_PASSWORD: example
    #volumes:
     # - type: volume
      #  source: psql_data
       # target: /var/lib/postgresql/data
    #networks:
     # - app
    #restart: always
  #inventory:
   # image: kellymarchewa/inventory_api
    #depends_on:
     # - db
    #ports:
    #  - 8080:8080
    #networks:
     # - app
    #restart: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
