#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 9001:9001 #dali ovaa porta ni treba ovde
#    depends_on:
#      - postgres_db
#  postgres_db:
#    image: "postgres:11.4"
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_PASSWORD: Nikolapass1212.

#
#version: '3'
#services:
#  db:
#    image: "postgres"
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Nikolapass1212.
#  app:
#    build: .
#    ports:
#      - "9001:9001"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=dizajn_proekt
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: Nikolapass1212.
#    depends_on:
#      - db